services:
  firefly-postgres:
    image: postgres:${FIREFLY_POSTGRES_VERSION}
    container_name: firefly-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${FIREFLY_POSTGRES_DB}
      POSTGRES_USER: ${FIREFLY_POSTGRES_USER}
      POSTGRES_PASSWORD: ${FIREFLY_POSTGRES_PASSWORD}
    volumes:
      - ./vol/firefly-postgres:/var/lib/postgresql/data
    networks:
      - firefly-private

  firefly-app:
    image: fireflyiii/core:${FIREFLY_VERSION}
    container_name: firefly-app
    restart: unless-stopped
    environment:
      APP_KEY: ${FIREFLY_APP_KEY}
      APP_URL: https://${FIREFLY_APP_HOSTNAME}
      APP_FORCE_SSL: true
      TRUSTED_PROXIES: "*"
      DB_CONNECTION: pgsql
      DB_HOST: firefly-postgres
      DB_PORT: 5432
      DB_DATABASE: ${FIREFLY_POSTGRES_DB}
      DB_USERNAME: ${FIREFLY_POSTGRES_USER}
      DB_PASSWORD: ${FIREFLY_POSTGRES_PASSWORD}
      MAIL_MAILER: smtp
      MAIL_HOST:  ${FIREFLY_SMTP_HOST}
      MAIL_PORT: ${FIREFLY_SMTP_PORT}
      MAIL_USERNAME: ${FIREFLY_SMTP_USER}
      MAIL_PASSWORD: ${FIREFLY_SMTP_PASS}
      MAIL_ENCRYPTION: tls
      MAIL_FROM: ${FIREFLY_SMTP_FROM}
      SITE_OWNER: ${FIREFLY_SMTP_FROM}
    volumes:
      - ./vol/firefly-app:/var/www/html/storage/upload
    depends_on:
      - firefly-postgres
    networks:
      - proxy-client-firefly
      - firefly-private

networks:
  proxy-client-firefly:
    name: proxy-client-firefly
    external: true

  firefly-private:
    name: firefly-private
    driver: bridge
    internal: true
